output frontendHosting_connectionString string = __frontendHostingDeploy__.outputs.connectionString
output frontendHosting_storageName string = __frontendHostingDeploy__.outputs.storageName
output frontendHosting_endpoint string = __frontendHostingDeploy__.outputs.endpoint
output frontendHosting_domain string = __frontendHostingDeploy__.outputs.domain
